// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Application = { name: string, comment: string, icon: string, exec: string, };
